name = "tg-comment-bot"
type = "javascript"
zone_id = ""
account_id = "e09da08efbe65ac347d8ae5f0f878607"
route = ""
workers_dev = true

[build]
command = "yarn && yarn run build"
[build.upload]
format = "service-worker"

[vars]
BOT_TOKEN = "1234567890:abcdefghijklmnopqrstuvwxyz1234567890"
WEBHOOK_SECRET = "/secret"
SET_WEBHOOK_SECRET = "/setWebhook"
DELETE_WEBHOOK_SECRET = "/deleteWebhook"
GET_WEBHOOK_INFO_SECRET = "/getWebhookInfo"
